[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node", "python"]

[build.nixpacksOptions]
nixPkgs = ["nodejs_18", "python310", "python310Packages.pip"]

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
